version: '3.9'
services:
  backend:
    image: '127.0.0.1:5000/multiroommusicplayer_backend' 
    build: .
    command:  "gunicorn Queens.wsgi:application --bind 0.0.0.0:8000 --workers=4"
    ports:
      - 8000:8000    
    volumes:
      - .:/app 
    depends_on:
      - db    
    env_file:
      - .env
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=""
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=s""
      - DATABASE=""
      - DATABASE_HOST=""
      - DATABASE_PORT=""

  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 1337:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
volumes:
  postgres_data:
